#!/usr/bin/python2.7

import os, sys, re

destroyThings = raw_input('Do you wish to destroy your garbage?')

if destroyThings == 'y':
	yourDir = raw_input('Enter the directory in which you would like to delete shit.')

	for file in os.listdir(yourDir):

		if re.search('urlBranch(.*)', file):
			os.remove(os.path.join(yourDir, file))
		elif re.search('Hexes(.*)', file):
			os.remove(os.path.join(yourDir, file))
		elif file == 'NextMatches':
			os.remove(os.path.join(yourDir, file))
		elif file == 'PossibleMatches':
			os.remove(os.path.join(yourDir, file))
		elif file == 'RCInfraredHexCodeDatabase':
			os.remove(os.path.join(yourDir, file))
